language: ruby
rvm:
- 2.2.2
- 2.3
- 2.4
- 2.5.0
- ruby-head
gemfile:
- gemfiles/activerecord_5_0.gemfile
- gemfiles/activerecord_5_1.gemfile
- gemfiles/activerecord_5_2.gemfile
before_script:
- export CI=true
- export CODECLIMATE_REPO_TOKEN=fc2954c6a30b02c5bf0bb7b03bef3a65249dba39403ea4e40acc05e604e8c967
before_install:
- gem update --system --no-document
- gem install bundler -v 1.16.1 --no-document
bundler_args: "--jobs=2"
script:
- bundle exec rspec
- bundle exec codeclimate-test-reporter
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: DXSWgq3btzGA6K+R2ra10x/Y9WMJ/OsZyYuofGFbEj+ozWSu525lcVajUTDt0hmYWUMeAGIocv4FekOJ/cTcfVeMd9H1tJRCy1tKM/fD/iOH3fwSQfoKqVfrFrePS1ktBnNBeuR85m6rjQEOFddgerVpJVl052+9c7LYrIbxkh8B6PJxL0AKaDf/WPMvmPIiVieZzjajkwa8mGitr5pmlofM8BbBtZ4ehKapRMeXY5lMZwtKWHBB0l7+D0926DpGb1xyAmmoATpADXZg5vNr5BZlwZK66KExddCt1KZCqf/n0xTHrMKnq96LPMtqslEZDwJwjCMJOqE0d5Eqxp5qGcHiOTANY2Ml2+EOoEnYMTWK5VT40uZ/GFAI9QM6yY2cxCu+gOt/jmUqm6Zv9lpa0nQC6OaMFd2lJPsn7JFsn4AnSfD7qg6L1hwVOzAM0H80WJmsqQyeFVTnnPIK7cltNhf+zz3UAUiBGrFld4UzrVZlLFWHm/57QTz5ed9EXu/wd47grmE+vTBimN82BBeXlsPtjgrRPo1BoDcjJfzYTugFiWZRCwykOZhZAzbtdTbD02jHrbjcOe5EXPyjBVQCqkfctKsunUxxCXp3nLVa0lhPOweSf5+vK+pH95+PV7oQgwCbo4k1l85zpFRaQlkA9cGE5vKoJ6LP7OKaxTN+haA=
matrix:
  allow_failures:
  - rvm: ruby-head

  # TODO: Remove after rails 5.2.0 is released!
  - gemfile: gemfiles/activerecord_5_2.gemfile
cache: bundler
sudo: false
dist: precise
