language: ruby
rvm:
- 2.2.2
- 2.3
- 2.4
- 2.5.0
- ruby-head
gemfile:
- gemfiles/activerecord_5_0.gemfile
- gemfiles/activerecord_5_1.gemfile
- gemfiles/activerecord_5_2.gemfile
before_script:
- export CI=true
#- export CODECLIMATE_REPO_TOKEN=
before_install:
- gem update --system --no-document
- gem install bundler -v 1.16.1 --no-document
bundler_args: "--jobs=2"
script:
- bundle exec rspec
#- bundle exec codeclimate-test-reporter
branches:
  only:
  - master
notifications:
  email: false
matrix:
  allow_failures:
  - rvm: ruby-head

  # TODO: Remove after rails 5.2.0 is released!
  - gemfile: gemfiles/activerecord_5_2.gemfile
cache: bundler
sudo: false
dist: precise
