name: test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: "0 10 * * 5" # JST 19:00 (Fri)

jobs:
  test:
    runs-on: ubuntu-latest

    container: ${{ matrix.ruby }}

    strategy:
      fail-fast: false

      matrix:
        ruby:
          - ruby:2.2
          - ruby:2.3
          - ruby:2.4
          - ruby:2.5
          - ruby:2.6
          - ruby:2.7
          - ruby:3.0
          - ruby:3.1
          - rubylang/ruby:master-nightly-bionic
        gemfile:
          - rails_5_0
          - rails_5_1
          - rails_5_2
          - rails_6_0
          - rails_6_1
          - rails_7_0
        include:
          - ruby: rubylang/ruby:master-nightly-bionic
            allow_failures: "true"

        exclude:
          # Rails 6.0+ requires Ruby 2.5+
          - ruby:    ruby:2.2
            gemfile: rails_6_0
          - ruby:    ruby:2.3
            gemfile: rails_6_0
          - ruby:    ruby:2.4
            gemfile: rails_6_0
          - ruby:    ruby:2.2
            gemfile: rails_6_1
          - ruby:    ruby:2.3
            gemfile: rails_6_1
          - ruby:    ruby:2.4
            gemfile: rails_6_1

          # Rails 7.0+ requires Ruby 2.7+
          - ruby:    ruby:2.2
            gemfile: rails_7_0
          - ruby:    ruby:2.3
            gemfile: rails_7_0
          - ruby:    ruby:2.4
            gemfile: rails_7_0
          - ruby:    ruby:2.5
            gemfile: rails_7_0
          - ruby:    ruby:2.6
            gemfile: rails_7_0

          # Rails 5.x doesn't work on Ruby 3.0+
          - ruby:    ruby:3.0
            gemfile: rails_5_0
          - ruby:    ruby:3.0
            gemfile: rails_5_1
          - ruby:    ruby:3.0
            gemfile: rails_5_2
          - ruby:    ruby:3.1
            gemfile: rails_5_0
          - ruby:    ruby:3.1
            gemfile: rails_5_1
          - ruby:    ruby:3.1
            gemfile: rails_5_2

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v3

      - name: Cache vendor/bundle
        uses: actions/cache@v1
        id: cache_gem
        with:
          path: vendor/bundle
          key: v1-gem-${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ github.sha }}
          restore-keys: |
            v1-gem-${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.gemfile }}-
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - name: bundle update
        run: |
          set -xe
          bundle config path vendor/bundle
          bundle update --jobs $(nproc) --retry 3
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - name: Setup Code Climate Test Reporter
        uses: aktions/codeclimate-test-reporter@v1
        with:
          codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
          command: before-build
        if: matrix.ruby >= 'ruby:2.4'
        continue-on-error: true

      - name: Run test
        run: |
          set -xe
          bundle exec rspec
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - name: Teardown Code Climate Test Reporter
        uses: aktions/codeclimate-test-reporter@v1
        with:
          codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
          command: after-build
        if: matrix.ruby >= 'ruby:2.4' && always()
        continue-on-error: true

      - name: Slack Notification (not success)
        uses: lazy-actions/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: ${{ format('*build* ({0}, {1})', matrix.ruby, matrix.gemfile) }}
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: lazy-actions/slatify@master
        if: always()
        continue-on-error: true
        with:
          job_name: '*build*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
